spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tracker_db
    username: tracker_user
    password: tracker_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


store:
  distance:
    radius: 100